name: Python application

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'  
      - '.github/workflows/python-app.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '.github/workflows/python-app.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest 

    - name: Run tests
      if: ${{ github.event.inputs.ShouldRunTests == 'true' }}
      run: |
        pytest test_main.py
      env:
        ShouldRunTests: ${{ github.event.inputs.ShouldRunTests }}

    - name: Run custom script
      run: |
        python script.py

